# Dodaj ten folder do ścieżki wyszukiwania klas i konfiguracji
BBPATH .= ":${LAYERDIR}"

# Znajdź i dodaj wszystkie przepisy (.bb i .bbappend) z folderów 'recipes-*'
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

# Nazwa identyfikacyjna naszej warstwy
BBFILE_COLLECTIONS += "meta-openstlinux-custom"

# Powiąż znalezione pliki z tą warstwą

BBFILE_PATTERN_meta-openstlinux-custom = "^${LAYERDIR}/"

# W zmiennej BBFILES (linijkę wyżej w pliku) użyłeś ogólnego zapisu z gwiazdkami (recipes-*/*/*.bb), żeby system 
# automatycznie wyszukał przepisy.

# Ta linijka (BBFILE_PATTERN) bierze te wszystkie znalezione pliki i mówi: „Jeśli ścieżka danego pliku zaczyna się od # mojego folderu, to przypisz ten przepis do mojej warstwy meta-openstlinux-custom”. Dzięki temu BitBake wie, który 
# przepis należy do której warstwy i może mu przypisać odpowiedni priorytet (np. ten poziom 6, który masz ustawiony 
# niżej).


# Priorytet nadpisywania (im wyższy, tym ważniejsze są Twoje pliki)
BBFILE_PRIORITY_meta-openstlinux-custom = "6"

# Ta warstwa wymaga do działania podstawowej warstwy 'core'
LAYERDEPENDS_meta-openstlinux-custom = "core"

# Warstwa działa tylko z wersją Yocto "Scarthgap" (wersja 5.0 LTS)
LAYERSERIES_COMPAT_meta-openstlinux-custom = "scarthgap"
